# Generated by Django 5.2 on 2025-05-15 15:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('patient_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('kelamin', models.PositiveSmallIntegerField(choices=[(0, 'Perempuan'), (1, 'Laki-laki'), (2, 'Non-biner')], help_text='0: perempuan, 1: laki-laki, 2: non-biner')),
                ('tanggal_lahir', models.DateField()),
                ('phone_number', models.CharField(help_text='nomor telpon indonesia', max_length=15)),
                ('alamat', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('available', 'Available'), ('assigned', 'Assigned'), ('reading', 'Reading'), ('error', 'Error'), ('offline', 'Offline')], default='available', max_length=20)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('assigned_patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_node', to='main_app.patients')),
            ],
        ),
        migrations.CreateModel(
            name='Readings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('alcohol', models.FloatField(blank=True, null=True)),
                ('urine', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Dehydrated'), (1, 'Enough'), (2, 'Well')], null=True)),
                ('berat', models.FloatField(blank=True, null=True)),
                ('tinggi', models.FloatField(blank=True, null=True)),
                ('bmi', models.FloatField(blank=True, null=True)),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.nodes')),
                ('patient_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='main_app.patients')),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('doctor', 'Doctor'), ('nurse', 'Nurse'), ('admin', 'Admin')], max_length=10)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
