# Generated by Django 5.2 on 2025-05-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_staffprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
